### ISSUE TITLE
Mark multiple files and open them

### ISSUE THREAD

**Issue by nayefc** [yasuyk/helm-git-grep#13]
Does anyone know if its possible to mark multiple files and open them with `helm-git-grep`?

**Comment by joeheyming** [comment]
I would just save helm-git-grep to a a grep buffer.  That stays around and you can jump between files in that buffer with F6

**Comment by yasuyk** [comment]
@nayefc, As @joeheyming said, `helm-git-grep` can save result of grep to a grep buffer which name is `*hggrep*`. You can jump each results by `compile-goto-error`, `previous-error` and `next-error`.

I close this issue. Please reopen if necessary.
