### ISSUE TITLE
Please tag a version for melpa-stable

### ISSUE THREAD

**Issue by stsquad** [yasuyk/helm-git-grep#14]
Could you tag your current version with a melpa-stable compatible tag (see version-to-list) so it can be included in MELPA stable?

**Comment by mdorman** [comment]
I actually browsed by to make this same request.

**Comment by yasuyk** [comment]
@stsquad @mdorman Sorry for the very very delayed response. 

I tagged 0.6.3. `helm-git-grep` is available from MELPA stable now. :smile:

**Comment by stsquad** [comment]
@yasuyk thanks ;-)
