### ISSUE TITLE
Spurious "the mark is not set now, so there is no region" errors

### ISSUE THREAD

**Issue by patrickt** [yasuyk/helm-git-grep#22]
Hi there,

Seemingly at random, helm-git-grep-at-point stops working when the point is over a word and I want to grep for occurrences of that word. Sometimes it works, and sometimes it fails with `"The mark is not set now, so there is no region"`. I can work around this by highlighting the word around the current point, but it tends to throw me off. Am I doing something wrong, or is this a bug?

**Comment by yasuyk** [comment]
@patrickt Thank you for reporting this issue, but I can not reproduce it. Could you tell me your OS version and Emacs version?

**Comment by patrickt** [comment]
@yasuyk This appears to have fixed itself randomly. I have no idea what the original issue was, but it doesn't matter now! Thank you for your response and for a great package.
