### ISSUE TITLE
Feature request: allow to turn off searching in submodules

### ISSUE THREAD

**Issue by fourier** [yasuyk/helm-git-grep#25]
I have **boost** in submodules and therefore searching for anything in the code base itself takes too much time.
Would be great to have a variable to turn off searching in submodules.

**Comment by yasuyk** [comment]
@fourier Sorry for delay response.  I have implemented this feature.  You can exclude submodules by customizing [`helm-git-grep-sources`](https://github.com/yasuyk/helm-git-grep#helm-git-grep-sourcesdefault-helm-source-git-grep-helm-source-git-submodule-grep).
