### ISSUE TITLE
helm-elscreen.el was removed from helm

### ISSUE THREAD

**Issue by tarsius** [yasuyk/helm-git-grep#34]
Unfortunately https://github.com/emacs-helm/helm/commit/6193cc4d5928156180a279e73bd38633dd7e5bee doesn't really say why. Hopefully dropping support from your package isn't more involved than what that commit did to `helm-grep.el`.

**Comment by buzzz321** [comment]
Would be nice if mepla/marmelade package got updated too with this patch

**Comment by tarsius** [comment]
@buzzz321 Melpa will automatically pick it up once it is merged. Someone will have to upload it to Marmalade, which is impossible to do if you don't already have an account there, because its maintainer does not answer account creation requests (or any other request for that matter).

@PythonNut Thanks! @yasuyk doesn't seem very active here - does anyone else have commit access?

**Comment by PythonNut** [comment]
@tarsius alternatively, if this continues, we could switch MELPA to point at my fork, although I don't expect I'll be enhancing it very much, I personally use it, so I'll at least keep it from breaking.

**Comment by tarsius** [comment]
I think that's a good idea, but let's give @yasuyk a change to chime in.

**Comment by yasuyk** [comment]
@PythonNut @tarsius Sorry for my late reply. I think that's a good idea too. It' helpful for me.

@PythonNut If you're a necessary, I will give you commit access. Perhaps, you are of course to switch MELPA to point at your fork.

**Comment by tarsius** [comment]
Thanks!

**Comment by stsquad** [comment]
Now this is merged could we have a new release tagged for the MELPA stable users?

**Comment by sungwonida** [comment]
Oh.. helm-git-grep come to show me a message like "Cannot open load file: No such file or directory, helm-elscreen". As a melpa-stable user I didn't even expected to get such an error. I want to have a new release ASAP.
