### ISSUE TITLE
[functional request] auto insert the symbol under cursor

### ISSUE THREAD

**Issue by zw963** [yasuyk/helm-git-grep#7]
I use helm-git-grep frequently, this functionality can save so many COPY and PASTE times.

**Comment by CyberShadow** [comment]
There is an opportunity for improvement here: specify the symbol under cursor as the "default value", so that it can be pasted using M-n. Many other completing-read / helm users provide a default value already.

**Comment by zw963** [comment]
@CyberShadow , Seem like this function is exist.

```sh
M-x helm-git-grep-at-point

Helm git grep with symbol at point. if submodules exists, grep submodules too.
```

**Comment by CyberShadow** [comment]
@zw963 I think that there is a simpler way. Here is what I meant: https://github.com/yasuyk/helm-git-grep/pull/29
